### ISSUE TITLE
Drop down menu unreadable for some themes

### ISSUE THREAD

**Issue by ashemsay** [2xx04/lemmy-ui-themes#1]
First of all, thanks for sharing those, I find it refreshing to give a new look to my lemmy :)

Just a small issue though with some of the dark themes, the drop down menu is not readable as we have white text over white background:
- solar
- vaporwave-dark

Here is an example:
![image](https://user-images.githubusercontent.com/8015125/162816160-0b399430-1fe7-41e4-87b4-4f58a177d6ab.png)

**Comment by 2xx04** [comment]
I didn't really understand how bootstrap works before, so I added css paths. you should be able to use newest theme just fine on top of anything.

none of my themes are based on vaporwave or solar though, are you, making a new theme or something?, be sure to use something that it's based on in the lemmy settings for those older ones.

**Comment by ashemsay** [comment]
haha forget about it, I never saw there already where themes with lemmy, I installed the themes on my test instance and went to my prod instance to check and when I saw themes I though that was it... silly me.
